version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=compliancescannerdb;Username=scanuser;Password=SecurePass123!
      - Seq__ServerUrl=http://seq:80
    depends_on:
      - postgres
      - redis
      - seq
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
      
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=compliancescannerdb
      - POSTGRES_USER=scanuser
      - POSTGRES_PASSWORD=SecurePass123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  seq_data: