version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=compliancescannerdb
      - POSTGRES_USER=scanuser
      - POSTGRES_PASSWORD=SecurePass123!
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_dev_data:/data
    restart: unless-stopped

volumes:
  postgres_dev_data:
  seq_dev_data: